### PR TITLE
fix(tauri): kill gptme-server subprocesses and orphans on exit

### LINKED ISSUE #2260: bug(tauri): gptme-server sidecar persists after gptme-tauri quits
## Problem

After quitting `gptme-tauri`/`gptme.app`, the `gptme-server` sidecar process continues running as an orphan (visible via `ps`):

```
501 40993     1   0  4:15PM ??         0:00.43 /Applications/gptme.app/Contents/MacOS/gptme-server --cors-origin ...
501 41027 40993   0  4:15PM ??         0:11.10 /Applications/gptme.app/Contents/MacOS/gptme-server --cors-origin ...
```

This means:
- Port 5700 remains occupied after quitting the app
- The reuse-on-restart logic added in #2258 quietly reuses the leftover server (which is fine), but the zombie process is never cleaned up
- Repeated quit/restart cycles could accumulate orphaned processes

## Expected Behaviour

When the Tauri app exits (clean exit, crash, or force-quit), all spawned `gptme-server` sidecar processes should be terminated.

## Likely Fix

Tauri has a `on_window_event` hook and/or `setup` cleanup path where we can explicitly kill tracked `ServerProcess` children on `CloseRequested` / app exit. The `ServerProcess` state in `lib.rs` already holds the child handle — we just need to wire up termination.

Also worth checking whether `CommandChild` in `tauri-plugin-shell` survives parent exit without explicit kill — if not, it may be a Tauri bug or configuration issue.

## Related

- PR #2258 added crash-recovery by reusing an existing responsive server
- Flagged by Erik in #2258 review: `gptme-server` visible in `ps` after quit

### PR DESCRIPTION
**Pull request by TimeToBuildBob**
## Summary

Fixes #2260 — two gaps in `cleanup_server_process` that left `gptme-server` processes alive after the Tauri app exits.

### Gap 1: subprocesses survive `child.kill()`

`child.kill()` sends SIGKILL to the *direct* child only. `gptme-server` may spawn subprocesses (e.g. uvicorn workers), which become orphans that keep port 5700 occupied.

**Fix**: new `kill_subprocesses(pid)` called before `child.kill()`:
- Unix: `pkill -9 -P <pid>` (direct children of the sidecar)
- Windows: `taskkill /F /T /PID <pid>` (full process tree)

### Gap 2: reuse path (from #2258) leaves no tracked handle

When `spawn_server_sidecar()` detects a responsive existing server and returns `Ok(())` without spawning, `ServerProcess` stays `None`. On exit, `cleanup_server_process` found no child and did nothing — the leftover server persisted.

**Fix**: new `kill_server_on_port(port)` called when `guard` is `None`:
- Unix: `lsof -ti:<port>` to find PIDs, then `kill -9` each (plus their children)
- Windows: `netstat -ano` to find PID, then `taskkill /F /T /PID`

Both helpers are `#[cfg(unix)]`/`#[cfg(windows)]` gated with a no-op stub for any other platform.

## Test plan

- [ ] `cargo test` passes on a desktop build (requires GTK3 dev libs — CI will validate)
- [ ] Build gptme-tauri; normal startup + quit leaves no `gptme-server` in `ps`
- [ ] Kill `gptme-tauri` via `pkill`, restart — app starts without dialog; quit leaves no orphan processes
- [ ] Verify port 5700 is free after quitting the app via Cmd+Q / dock quit / X button

### CODE REVIEW

**Comment by TimeToBuildBob** [comment]
Addressed both P1s in 0adae3a94:

**P1 — `stop_server` IPC leaves orphan subprocesses**: Added `kill_subprocesses(child.pid())` before `child.kill()` in `stop_server`, mirroring what `cleanup_server_process` already does.

**P1 — `else` branch kills unrelated process**: Refactored `ServerProcess` to carry `owns_port: Arc<AtomicBool>`. Set to `true` when we start or reuse a server, left `false` when startup fails with a non-responsive port conflict. The `kill_server_on_port` call in `cleanup_server_process` is now guarded by `owns_port.load()`, so we never kill a process we didn't start.

**Comment by ErikBjare** [comment]
@greptileai review

**Comment by TimeToBuildBob** [comment]
Addressed both remaining Greptile concerns in 497e585:

**Unix — lsof self-kill**: `lsof -ti :5700` returns all PIDs with sockets on that port, including gptme-tauri's own WebView (an established client connection). Added a `my_pid = std::process::id()` check and `continue` to skip our own PID.

**Windows — port substring match**: Replaced `line.contains(":5700")` with field-level parsing. Split by whitespace, take `col[1]` (the local address field, e.g. `0.0.0.0:5700`), and check `ends_with(":5700")` — so `:5700` no longer falsely matches `:57001`.

**Comment by TimeToBuildBob** [comment]
@greptileai review

File: tauri/src-tauri/src/lib.rs [hunk 1]
```diff
@@ -496,6 +496,10 @@ fn kill_subprocesses(pid: u32) {
 // (the spawn_server_sidecar reuse path).
 #[cfg(unix)]
 fn kill_server_on_port(port: u16) {
+    // lsof returns all PIDs with any socket on the port, including established
+    // client connections (e.g. the Tauri WebView itself).  Skip our own PID to
+    // avoid self-killing the Tauri process during cleanup.
+    let my_pid = std::process::id();
```
Comment (ErikBjare) [inline tauri/src-tauri/src/lib.rs:506]: Doesn't the server process use another child PID?

**Comment by TimeToBuildBob** [comment]
Two remaining Greptile P1s addressed in 4e75a3c:

**P1 — `stop_server` leaves `owns_port` stale**: Added `state.owns_port.store(false, Ordering::Relaxed)` synchronously after `child.kill()` in `stop_server`. Without this, if the user stops via IPC and quits before the async `Terminated` handler fires, `cleanup_server_process` sees `guard==None` + `owns_port==true` and calls `kill_server_on_port` against whatever process later binds to port 5700.

**Unix — `lsof -ti` scope**: Switched to `lsof -ti :<port> -sTCP:LISTEN` which restricts output to the process actually *listening* on the port, excluding established client connections (WebView renderer, etc.). The `my_pid` self-kill guard is kept as defence-in-depth.

**Comment by TimeToBuildBob** [comment]
@greptileai review
